version: '3.8'

services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    ports:
      - "8888:8888"
    volumes:
      - .:/app
      - jupyter-data:/home/jovyan
    environment:
      - JUPYTER_TOKEN=your_secure_token
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G

volumes:
  jupyter-data: