
version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile      # your web‑app Dockerfile
    container_name: web_app
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      SECRET_KEY: "your_super_secret_key"
      SUPABASE_URL: "https://okhrguykcmeaakxclkbl.supabase.co"
      SUPABASE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9raHJndXlrY21lYWFreGNsa2JsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwNTM0NzMsImV4cCI6MjA1NTYyOTQ3M30.XytMV4yJ5GMmhD_53E4rAByqBSY8GcqD1C0B3IWBjh8"
    volumes:
      - .:/app

  mlp:
    build:
      context: .
      dockerfile: Dockerfile_mlp  # the MLP Dockerfile
    container_name: mlp_eeg
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    environment:
      INPUT_CSV: /app/data/test_mlp.csv
      OUTPUT_MODEL: /app/models/best_model.joblib
    # default runs mlp_eeg_train.py; override to run test:
    # command: ["python", "mlp_eeg_test.py"]
    command: ["python", "mlp_eeg_train.py"]
